version: '3'
services:

  main:
    # @TODO: Comment out the following line if you don't need MySQL
    #        or add your dependencies
    #        More detail:
    #        https://docs.docker.com/compose/startup-order/
    #        https://github.com/vishnubob/wait-for-it
    command: 'bash ./wait-for-it.sh mysql:3306 -t 0 -s -- ${CUSTOM_CMD}'
    ports: []
    environment:
      - NODE_ENV=development
    volumes: []
    links: []
    depends_on: []

  # @TODO: Uncomment the following "placeholder" service if you don't need Redis
  # redis:
  #   build:
  #     context: ../
  #     dockerfile: configs/Dockerfile-empty
  #   command: 'sleep 86400'

  # @TODO: Uncomment the following "placeholder" service if you don't need MongoDB
  # mongo:
  #   build:
  #     context: ../
  #     dockerfile: configs/Dockerfile-empty
  #   command: 'sleep 86400'

  # @TODO: Uncomment the following "placeholder" service if you don't need initial data for MongoDB
  # mongoimport:
  #   build:
  #     context: ../
  #     dockerfile: configs/Dockerfile-empty
  #   command: 'sleep 86400'

  # @TODO: Uncomment the following "placeholder" service if you don't need MySQL
  # mysql:
  #   build:
  #     context: ../
  #     dockerfile: configs/Dockerfile-empty
  #   command: 'sleep 86400'
